project_id = "xtqjesrpyrnijyavdrux"

[functions.send-newsletter-confirmation]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.fragrance-recommender]
verify_jwt = false